language: python
script:
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: OjOf+fzpOq4PL4bt9cp5fH9I2lz3Pjw+CKuzEnksGimfBqTCQuc/ikG6z9TMeOfKGfKre37bq5fOSSXsfFCkJjVJGsQWl61H8yyzj/bbalPfUqPeHaAS5Q0cVTGr5Jrtv+1M6Osg1Lk34UBjgXol9Id341yhbBZhetbNzlwNOe4E/25KoTp3Yr4lXPm5D2mYstGkreFJhBPZsyih11Zosy7Yn4RKL05qEiXgldEd0cV2LZ2EPT2dfpYXlKyhWqnxiky1tj2GzvhM9vaCoZhvTKSRvKdaG3H2pP0edKYRt3k/hOd6r63Ebln/3kqN9YCfSYoYq6Waks11czkCQU1RZTFE2IRhEh2MChUcj2lTAryA0W2ZOCr45O5U8VFAkoAWqwqyQ0HFRbVSdzch2yD92MFlBvN7jK/byfP9QPe7o2GyDDWST28/1oKohfFgIm3BdijZkBsevGn0/SNgjSkzapJCYytX5C/IySCawKvcYmhWcPQIGLUKUZCLbSQ6xdN3fDTR9CSo+D0fTewKVsk9R8WUYsvA5wmHI/K/KJaouDRBTO3ewN9Y2zcMhZ9kEy2O2DBInmHxfTTZ3nKMB3S0ja8cPUpDAzW3aRib0JktYbs4glY+gpslWBsBlZgKLi2O964dvHz9e9RIAAu5G8oYhcOyWerZQF+lQ/zHE6SItzE=
  distributions: "sdist bdist_wheel"
  skip_existing: true
